### PR TITLE
Feature/134209519/landing page

### PR DESCRIPTION
**Pull request by ngozi-ekekwe**
#### What does this PR do?

It replaces the existing landing page with an effective UI/UX

#### Description of Task to be completed?

Replace the content of the index.html with new html content, and also add styling

#### How should this be manually tested?

visit this link on heroku https://kissa-cfh-staging-pr-44.herokuapp.com/#!/

#### Any background context you want to provide?

N/A

#### What are the relevant pivotal tracker stories?

#134209519

### CODE REVIEW

**Review by tomily1 — APPROVED** [review]
**Nitpick**
Avoid trailing spaces in subsequent PR's

I approve this PR and I think it can be merged

**Review by andela-jare — DISMISSED** [review]
Remove commented code

**Comment by oagboola** [comment]
@andela-jare its 'code' not 'codes'

**Comment by oagboola** [comment]
@andela-nekekwe check out the houndCi issues and update

**Review by oagboola — APPROVED** [review]
LGTM

**Pull request merged**
